// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvyokkipfoccvlvpliqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eW9ra2lwZm9jY3ZsdnBsaXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTQyMjUsImV4cCI6MjA2NjUzMDIyNX0.sHh7-lH7LuBc_2wJdU68qH6tQOkQJTtgWRxQmHc73pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);